# hydra:
#   run:
#     dir: ./my_output_dir  # save outputs to custom dir

root_dir: ${hydra:runtime.cwd}  # 运行代码的根目录


dataset_name: TinyStories     # `TinyStories` or `owt`, change as needed
dataset_split: train          # `train` or `valid`, change as needed

data_dir: ${root_dir}/data/${dataset_name}
txt_dir: ${data_dir}/txt
dat_dir: ${data_dir}/dat
train_txt_path: ${txt_dir}/train.txt
valid_txt_path: ${txt_dir}/valid.txt

input_path: ${txt_dir}/${dataset_split}.txt   # txt data for training tokenizer
train_dat_path: ${dat_dir}/train.dat
valid_dat_path: ${dat_dir}/valid.dat

tokenizer_dir: ${root_dir}/tokenizers/${dataset_name}_${dataset_split}/ # save path for tokenizer
vocab_path: ${tokenizer_dir}/vocab.pkl
merges_path: ${tokenizer_dir}/merges.pkl

vocab_size: 10_000
special_tokens: ["<|endoftext|>"]

# encode config
batch_size: 10000 # 4096
n_workers: 20 # 8