[project]
name = "clean-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "accelerate>=1.8.1",
    "torch>=2.7.1",
    "transformers>=4.53.1",
]
