[project]
name = "clean-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.8.1",
    "hydra-core>=1.3.2",
    "transformers>=4.53.1",
]
